#include <QtGui>
#include <iterator>
#include <stdlib.h>
#include <qradiobutton.h>
#include "piechartdialog.h"
#include <iostream>
#include <math.h>

/*
 * Constuctor
 * It set up the title and the size of the dialog, creates two buttons
 * and connect them with switchValue method, creates vertical scrollbar,
 * and connect it with scrollTo method.
 */

int yEnd;
piechart::piechart(QWidget *parent) : QWidget(parent)
{
 setWindowTitle("Pie Chart");
 setFixedSize(650,600);

 yOrigin=10;
 temp=0;
 yEnd=-1;

 //Print Button
 printButton = new QPushButton("Print", this);
 printButton->setGeometry(QRect(QPoint(20,550),QSize(120,20)));
 connect(printButton, SIGNAL(pressed()),this,SLOT(printButtonPushed()));

 value1Button = new QRadioButton("",this);
 value2Button = new QRadioButton("",this);
 value1Button->setGeometry(QRect(QPoint(50,400),QSize(120,60)));
 value2Button->setGeometry(QRect(QPoint(180,400),QSize(120,60)));
 buttonGroup=new QButtonGroup(this);
 buttonGroup->addButton(value1Button);
 buttonGroup->addButton(value2Button);
 connect(buttonGroup,SIGNAL(buttonClicked(int)),this,SLOT(switchValue()));

 layout = new QHBoxLayout(this);
 verticalBar = new QScrollBar(Qt::Vertical);
 layout->addWidget(verticalBar);

 connect(verticalBar,&QScrollBar::valueChanged,this,&piechart::scrollTo);
 printf("Pie Test");
}

void piechart::printButtonPushed()
{
    QPrinter printer;

    QPrintDialog *dialog = new QPrintDialog(&printer, this);
    dialog->setWindowTitle(tr("Print Document"));

    if (dialog->exec() != QDialog::Accepted)
        return;

    QPixmap pixmap = QPixmap::grabWidget(this, 0, 0, -1, -1);
    QPainter painter;
    painter.begin(&printer);
    painter.drawImage(0, 0, pixmap.toImage());
    painter.end();
}
/*
 * The method gets data from GraphClass object using iterator,
 * creates four qvectors that store value1,value2,title and colors,
 * decides what type of GraphClass object it is and paint the piechart
 * dialog.
 * The colors is generated by random number of red, green and blue.
 */
void piechart::setData(GraphClass *graph,int start,int end)
{
    QVector<int> value1;
    QVector<int> value2;
    QVector<string> title;
    QVector<QColor> color;
    list<list<BarValue> > * readyForGraph = graph->getRange();
    list<list<BarValue> >::iterator i1 = readyForGraph->begin();

    while (i1 != readyForGraph->end()) {
        list<BarValue>::iterator i2 = i1->begin();
        while (i2 != i1->end()) {
            title.push_back(i2->title);
            value1.push_back(i2->yValue1);
            value2.push_back(i2->yValue2);
            color.push_back(QColor(qrand()%256,qrand()%256,qrand()%256,255));
            ++ i2;
        }
        ++ i1;
    }

    this->startDate = start;
    this->endDate = end;
    this->graphValue1=value1;
    this->graphValue2=value2;
    this->graphTitle=title;
    this->graphColor=color;
    graphValue=graphValue1;

    if(graphTitle.at(0)=="Grant - PR"){
        value1Button->setText("Total Number");
        value2Button->setText("Total Amount");
        typeNum=4;
    }
    else if(graphTitle.at(0)=="Teaching - PME"){
        value1Button->setText("Total Number of Student");
        value2Button->setText("Total Number of Teaching Hours");
        typeNum=4;
    }
    else if(graphTitle.at(0)=="Pres - Lectures"){
        value1Button->hide();
        value2Button->hide();
        typeNum=4;
    }
    else{
        value1Button->hide();
        value2Button->hide();
        typeNum=21;
    }
    repaint();
}

/*
 * This method is used to set up the page step of the scroll bar.
 * The length of the page step is between 10 and 1000.
 * If y-cordinate(the end point) is smaller than the height of
 * the screen,which is 600, set the page step to be the height.
 * If the y-cordinate is bigger than 1190, set the page step to be
 * 10.Otherwise, the page step will vary depending on y-cordinate.
 * When the page step has been set up, repaint the dialog
 */
void piechart::scrollTo(){
    if(yEnd < 0){
        yEnd=yCordinate;}
    verticalBar->setMinimum(0);
    if(yEnd<=600){
        verticalBar->setMaximum(601);
        verticalBar->setPageStep(600);
    }
    else if(yEnd>1190){
        verticalBar->setMaximum(yEnd-590);
        verticalBar->setPageStep(10);
    }
    else{
        verticalBar->setMaximum(yEnd-600);
        verticalBar->setPageStep(1200-yEnd);
    }


    yOrigin=yOrigin-verticalBar->value()+temp;
    temp=verticalBar->value();

    repaint();
}

/*
 * This method is called when either two buttons is clicked,
 * then switches the value.
 */
void piechart::switchValue(){
    if(value1Button->isChecked()){
        graphValue=graphValue1;
    }
    else{
        graphValue=graphValue2;
    }

    repaint();
}

/* paintEvent method paints piechart dialog
 * It firstly draw the rectangles that represents each pie slice and
 * add text next to them. Then it takes the value from the qvector and
 * draw each pie slice depending on the its percentageof the whore pie,
 * and add value on each slice.
 * If there is no value in the qvector, a white eclipse will be painted.
 * The rectangle that has no value will not be painted.
 */
void piechart::paintEvent(QPaintEvent *event)
{

    QPainter painter(this);
    QRect size(10,10,280,280);

    int count = graphValue.size();
    double sum = 0,startAng = 0;
    double percent,angle,endAng;

    //draw a white eclipse when there is nothing
    if(count==0){
        painter.setBrush(Qt::white);
        painter.drawPie(size,360,5760);
    }

    else{
        for(int i = 0; i<count;i++){
        sum+=graphValue[i];
        }

        painter.setPen(QPen(Qt::black,1));

        int start = startDate;

        //draw the index rectangles

        yCordinate = yOrigin;
        for(int i = 0;i<count;i++){
            if(i%typeNum==0&&i!=0){
                start++;
            }
            if(graphValue[i]!=0){
            painter.setBrush(graphColor[i]);
            painter.drawRect(350,yCordinate,30,20);
            painter.drawText(QPoint(390,yCordinate+12),QString::number(start)+"-");
            painter.drawText(QPoint(420,yCordinate+12),QString::number(start+1));
            painter.drawText(QPoint(460,yCordinate+12),QString::fromStdString(graphTitle[i]));
            yCordinate+=30;
            }
            else{
                continue;
            }
        }

        //draw the pie slices and add the number or amount on the specific slices
        for(int i = 0;i<count;i++)
        {
            if(graphValue[i]!=0)
            {
            percent = graphValue[i]/sum;
            angle = 360*percent;
            endAng = startAng + angle;
            painter.setBrush(graphColor[i]);
            painter.drawPie(size,startAng*16,angle*16);
            painter.drawText(QPoint(150+cos((startAng+angle/2)*3.14/180)*70,150-sin((startAng+angle/2)*3.14/180)*70),QString::number(percent*100)+"%");
            startAng = endAng;
            }
        }
    }
}

